name: dose_plus
description: 'A new Flutter project.'
version: 1.0.0+1

environment:
    sdk: ^3.7.2

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    sqlite3_flutter_libs: ^0.5.32
    drift: ^2.26.1
    drift_flutter: ^0.2.4
    path_provider: ^2.1.5
    path: ^1.9.1
    provider: ^6.1.5
    collection: ^1.19.1

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0
    build_runner: ^2.4.15
    drift_dev: ^2.26.1

flutter:
    uses-material-design: true
